### ISSUE TITLE
Click to Call not working for some sites 

### ISSUE THREAD

**Issue by adamf-int** [intulse/intulse-app-beta#10]
There are multiple issues:

When you click on the click to call extension icon in Chrome, it says you are logged in as "undefined."

Click to call seems to work on websites where the phone number is formatted with code: (xxx) xxx-xxxx
BUT click to call does not work with phone numbers formatted with tel: +1-xxx-xxx-xxxx

**Comment by darrenhollick** [comment]
So, this is actually not related to V2 at all.  However, this plugin has not yet been updated for V2 so we might as well work on it and get it working with V2 and V1 at the same time since I don't really want to roll out a beta version of this browser extension.

**Comment by darrenhollick** [comment]
A new version of the Intulse Click to Call browser extension has been submitted for review to the Chrome Web Store.  It can take up to a few weeks for them approve the new extension and make it available to users.

The new extension has several notable changes in it:
 * The number matching pattern has improved to try to catch more numbers
 * The authentication process is even easier and if you're not authenticated the user is given some instructions
 * The Menu that appears when you click on the extensions icon has changed significantly for an improved user experience
 * The settings area of the extension has had it's user interface complete redesigned
 * When a user clicks on a phone number the extension will now check if they have the BETA App open and if the Virtual Phone is enabled and if so it will bring that tab/window into focus and immediately start an outbound call using the Virtual Phone.

I'm going to close this issue for assuming that this will all be resolved when Google approves the new extension for the Chrome web store.   As usual, if we find something isn't right then we can re-open this issue.
