### ISSUE TITLE
Call Flow Control Permissions

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/intulse-app-beta#11]
**Is your feature request related to a problem? Please describe.**

So I’ve started looking at the BETA and I’ve have to say, it’s coming along very nicely! One thing I did notice however, is that it may be helpful is for Admins on our side to have some control over what type of entries a person can use with the “Smart Monitoring” feature. Specifically, for Admins to be able to decide if we want our users to have access to some of the Call Flow Controls as shown here:

![image](https://user-images.githubusercontent.com/57546882/92255403-43ecec80-eea0-11ea-924b-06ba3a662a1a.png)

We have a couple users that could benefit from being able to see/monitor the Call Flow Controls setup, but we would prefer to control access to that specifically if possible. We can currently choose if a specific extension can be monitored, and by people or roles, but we don’t seem to have an option to choose who can monitor/use the Call Flow Controls.

**Describe the solution you'd like**
Develop permissions for Call flow controls.

**Comment by darrenhollick** [comment]
There is no question that this is a good enhancement to make.  I think it would be worth trying to get this before beta goes to production.

**Comment by darrenhollick** [comment]
The management front-end of this is complete and working.  Now @gdalam just needs to make the front-end and back-end Smart Monitoring tools respect the permissions.
