### ISSUE TITLE
Notifications Management

### ISSUE THREAD

**Issue by danmalone89** [intulse/intulse-app-beta#12]
**Is your feature request related to a problem? Please describe.**
Users are unable to manage what notifications they would like to subscribe to. Today I received numerous notifications in a row after a colleague submitted several faxes.

**Describe the solution you'd like**
There should be a Notifications view for all users that is separate from other views. Probably nested in the "More" menu would be ideal. Users should be able to manage notifications (turn on, turn off) for:

- Incoming Calls
- Voicemails
- Faxes (Received, Sent, Error Sending). Maybe allow only notifications for faxes the user sent, and not others in the organization unless specified.
- SMS.. etc. I don't use the SMS feature in Intulse so my opinion on how this would be managed is indifferent. 

**Describe alternatives you've considered**
Right now, it appears the only option is to disabled notifications completely.

**Comment by darrenhollick** [comment]
I like this suggested enhancement.

**Comment by darrenhollick** [comment]
This will require the storage of user preferences.  We should do that in a generic way.  I suggest a new table with the following structure:

**[Table] UserSettings**
 * UserId
 * Setting (NVARCHAR, 100, NOT NULL)
 * Value (NVARCHAR, 250, NOT NULL)

**Comment by darrenhollick** [comment]
The table has been created and the work has started in branch [issues/beta-12-darren-notification-management](/intulse/intulse/tree/issues/beta-12-darren-notification-management)
