### ISSUE TITLE
Better Voicemail Folders

### ISSUE THREAD

**Issue by danmalone89** [intulse/intulse-app-beta#20]
**Describe the solution you'd like**

- [ ] The ability to CRUD any voicemail folders, including the default folders. I'm going to go out on a limb and say most users are business users and don't need to organize voicemails into Friends or Family categories. Some may, but users shouldn't have an unnecessary long list of voicemail folders that are never used. You probably wouldn't want to remove default folders until users had the ability to add and delete their own custom folders.

- [ ] Add a Default Trash/Deleted folder where all voicemails go _before_ they are permanently deleted. Currently, deleted voicemails are permanently deleted. Maybe instead voicemails older than 90 days in the Trash folder could be automatically permanently deleted.

- [ ] Change Badge Colors to reflect voicemails that have been heard vs. voicemails that have not been heard. Or just make the badge more descriptive, like "2 New". Right now, that number is simply a count of the voicemails in that folder and not super helpful.  I'm not sure how you would ultimately mark a voicemail heard or unheard -- maybe after clicking the play button on the audio recording? 
![image](https://user-images.githubusercontent.com/8354943/93882763-47f17a80-fca6-11ea-8d7a-646b37b2b3f8.png)
![image](https://user-images.githubusercontent.com/8354943/93882715-390ac800-fca6-11ea-8820-c9534ff394f1.png)

- [ ] Ability to set a default voicemail folder for specific contacts. Add a dropdown select to the contact form, which displays a selection of existing folders.

**Comment by darrenhollick** [comment]
There's good stuff here.  We need to break these down into separate items so they are in more manageable sizes.

I'm going to close this issue since these are individually open.
* Custom Voicemail Folders #28
* Add a default Trash/Deleted voicemail folder #29
* Better voicemail badge indicators #30
* Default voicemail folder for contacts #31
