### ISSUE TITLE
Phone setting state not maintained on the UI

### ISSUE THREAD

**Issue by danmalone89** [intulse/intulse-app-beta#26]
**Describe the bug [required]**
The UI does not reflect the state of the phone settings after they have been changed and after the user has navigated away from the **My Phone** view, then back to the **My Phone** view. See GIF below.

**To Reproduce [required]**
1. Go to **My Phone**
2. Click on **CF on Busy** and enter extension number, click **Save**.
3. Go to **Voicemail** view, or any other view like **Contacts.**
4. Switch back to **My Phone**
5. Find **CF on Busy** switched off, with the ability to turn it on again. 

**Expected behavior [required]**
On switching back to the **My Phone** view, the user expects to see the toggled settings in the state which the user left it before leaving the view. 

**Actual behavior [required]**
The **CF on Busy** setting is showing an old state. Refreshing the page causes the UI to reflect the actual, correct state.

**Screenshots**
![chrome-capture](https://user-images.githubusercontent.com/8354943/94037704-3df57780-fd8b-11ea-9ee1-50662a498532.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 85.0.4183.121 (Official Build) (64-bit)

_Same behavior on Chrome Browser on mobile._

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android Version 10

**Comment by darrenhollick** [comment]
Frankly I'm shocked that this made it into the beta at all... this needs to get fixed right away.  Thank you so much Dan for the great catch!
