### ISSUE TITLE
Agencybloc contacts not showing in My Phone search

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/intulse-app-beta#27]
**Describe the bug [required]**
Agencybloc contacts not showing as autocomplete options when entering names in the Call field

**To Reproduce [required]**
1. impersonate Brian Platte from account 55202
2. Go to my phone screen
3. in the active call search contacts field type in "Ken"

**Expected behavior [required]**
Kenneth Luxton from Agencybloc will appear as an clickable option

**Actual behavior [required]**
Kenneth Luxton does not appear

**Comment by darrenhollick** [comment]
A fix for this has been completed and queued for deployment tonight.
