### ISSUE TITLE
Contact Search Improvements

### ISSUE THREAD

**Issue by danmalone89** [intulse/intulse-app-beta#7]
**Is your feature request related to a problem? Please describe.**
This is not related to a bug.

**Describe the solution you'd like**

- **Better visual differentiation of phone numbers in search results.** When searching for contacts in the "search or dial" input field on the "My Phone" view, the search results populated in the drop down selector should indicate which Redtail CRM phone number is the "Preferred" phone number. 

- **Indicate "Searching" or "Loading" when searching for contacts. If there are no results, tell the user there are no results found.**

[Phones by ContactID Fetch](https://api2.redtailtechnology.com/crm/v1/rest/help/operations/Phone_Fetch) has a `Preferred ` key value pair available.

Change this
![image](https://user-images.githubusercontent.com/8354943/92009817-ac0bc900-ed0e-11ea-86d8-be7e4758fe1e.png)

To something like this.
![image](https://user-images.githubusercontent.com/8354943/92011491-be870200-ed10-11ea-9ec3-be2a6e8e09e0.png)

**Describe alternatives you've considered**

- Without crowding the dropdown, you could bold whichever (if any) phone number is preferred. Or add an asterisk or star emoji.

**Additional context**
![image](https://user-images.githubusercontent.com/8354943/92011407-a4e5ba80-ed10-11ea-8e01-5ecff07e82c3.png)

**Comment by darrenhollick** [comment]
This a cool suggestion and at least most of this can be done easily so I will go ahead and schedule this.

**Comment by darrenhollick** [comment]
This change has been completed and will roll out tonight.

**Comment by danmalone89** [comment]
> This change has been completed and will roll out tonight.

You guys are awesome. Thanks for the quick response.
