### ISSUE TITLE
Redtail contact search not working

### ISSUE THREAD

**Issue by adamf-int** [intulse/intulse-app-beta#9]
Searching for Redtail contacts is not working.

Steps to replicate:
Impersonate Sean at Endevor
IN the call box, search for Sean or Amanda. There should be 5 Amandas that show up via Redtail.

**Comment by darrenhollick** [comment]
discovered this being caused by a paging issue when retrieving the contact cache.  Fix is being worked on.

**Comment by darrenhollick** [comment]
This has been fixed and should be rolled out tonight
